version: "3.8"

services:
  auctionservice:
    build:
      context: .
      dockerfile: AuctionService/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
