name: MSTest & Push to DockerHub

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run MSTests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0' 
      - name: Restore solution
        run: dotnet restore AuctionService/AuctionService.sln

      - name: Build solution
        run: dotnet build AuctionService/AuctionService.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test AuctionService/AuctionService.sln --no-build --configuration Release

  build_and_push:
    name: Build og push Docker image
    runs-on: ubuntu-latest
    needs: test
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      IMAGE_NAME: go-auctionservice
    steps:
      - uses: actions/checkout@v4

      - name: Set dynamic image version
        id: vars
        run: echo "IMAGE_VERSION=$(date +%Y%m%d)-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: AuctionService/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_VERSION}
          docker push ${DOCKER_USER}/${IMAGE_NAME}:latest
